name: "Lint, Build, Test"
on:
  push:
    branches-ignore:
      - main
jobs:
  Lint-Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install deps
        run: npm install

      - name: Typecheck
        run: npm run lint:typecheck

      - name: Lint
        run: npm run lint:check

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
